// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.Extensions.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using RCommon.Persistence.EFCore;
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using RCommon.Entities;
using MotherStar.Platform.Domain;

namespace MotherStar.Platform.Data
{
    public partial class MonitoringDbContext : RCommonDbContext
    {
        private readonly IConfiguration _configuration;
        private readonly ILoggerFactory _loggerFactory;

        public MonitoringDbContext(DbContextOptions<MonitoringDbContext> options)
            : base(options)
        {

        }

        public MonitoringDbContext(DbContextOptions<MonitoringDbContext> options, IConfiguration configuration, ILoggerFactory loggerFactory)
            : base(options)
        {
            if (options is null)
            {
                throw new ArgumentNullException(nameof(options));
            }

            _configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
            _loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
        }

        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            

            OnModelCreatingPartial(modelBuilder);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured && _configuration != null)

            {
                var connectionString = _configuration.GetConnectionString(DataStoreNamesConst.SeoDb);
                var logger = _loggerFactory.CreateLogger(nameof(MonitoringDbContext));
                logger.LogDebug("Connection string: {0}", connectionString);
                optionsBuilder.UseNpgsql(connectionString);
                optionsBuilder.UseLoggerFactory(this._loggerFactory);
            }

        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
