// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using MotherStar.Platform.Domain.SEO.Lighthouse.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Data.Configurations
{
    public partial class LighthouseProfileConfiguration : IEntityTypeConfiguration<LighthouseProfile>
    {
        public void Configure(EntityTypeBuilder<LighthouseProfile> entity)
        {
            BaseConfiguration.Configure(entity);
            entity.ToTable("LighthouseProfiles");
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByEmail)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.WebsiteUrl)
                .IsRequired()
                .HasMaxLength(255);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LighthouseProfile> entity);
    }
}
