// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using MotherStar.Platform.Domain.SEO.Lighthouse.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Data.Configurations
{
    public partial class PageAuditRequestConfiguration : IEntityTypeConfiguration<PageAuditRequest>
    {
        public void Configure(EntityTypeBuilder<PageAuditRequest> entity)
        {
            BaseConfiguration.Configure(entity);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.PageUrl)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.LighthouseProfileId)
                .HasColumnName("LighthouseProfileId")
                .IsRequired();

            entity.HasOne(d => d.LighthouseProfile)
                .WithMany(p => p.PageAuditRequests)
                .HasForeignKey(d => d.LighthouseProfileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PageAuditRequests_LighthouseProfiles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PageAuditRequest> entity);
    }
}
