// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using MotherStar.Platform.Domain.SEO.Lighthouse.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Data.Configurations
{
    public partial class PageAuditConfiguration : IEntityTypeConfiguration<PageAudit>
    {
        public void Configure(EntityTypeBuilder<PageAudit> entity)
        {
            BaseConfiguration.Configure(entity);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.PageUrl)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.PageAuditRequest)
                .WithMany(p => p.PageAudits)
                .HasForeignKey(d => d.PageAuditRequestId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PageAudits_PageAuditRequests");
            

            entity.HasOne(d => d.Status)
                .WithMany(p => p.PageAudits)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PageAudits_Statuses");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PageAudit> entity);
    }
}
