// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using RCommon.Entities;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Domain.SEO.Lighthouse.Models
{
    public partial class LighthouseProfile : BusinessEntity<Guid>
    {
        public LighthouseProfile()
        {
            PageAuditRequests = new HashSet<PageAuditRequest>();
        }

        public LighthouseProfile(Guid id, DateTime createdDate, string websiteUrl, string createdByEmail) : this()
        {
            Id=id;
            CreatedDate=createdDate;
            this.WebsiteUrl=websiteUrl;
            this.CreatedByEmail=createdByEmail;
        }

        public DateTime CreatedDate { get; set; }
        public string WebsiteUrl { get; set; }
        public string CreatedByEmail { get; set; }
        public virtual ICollection<PageAuditRequest> PageAuditRequests { get; set; }
    }
}
