// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using RCommon.Entities;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Domain.SEO.Lighthouse.Models
{
    public partial class PageAuditItem : BusinessEntity<Guid>
    {
        public Guid PageAuditId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ReferenceId { get; set; }
        public int AuditCategoryId { get; set; }
        public Guid StatusId { get; set; }
        public string Details { get; set; }

        public virtual PageAudit PageAudit { get; set; }
        public virtual Status Status { get; set; }
    }
}
