// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable //make compiler happy
using RCommon.Entities;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Domain.SEO.Lighthouse.Models
{
    public partial class PageAudit : BusinessEntity<Guid>
    {
        public PageAudit()
        {
            PageAuditItems = new HashSet<PageAuditItem>();
        }

        public PageAudit(Guid id):this()
        {
            Id=id;
        }
        public DateTime CreatedDate { get; set; }
        public Guid StatusId { get; set; }
        public double? Score { get; set; }
        public string? PageUrl { get; set; }
        public Guid PageAuditRequestId { get; set; }
        public string? AuditReport { get; set; }
        public int? Device { get; set; }

        public virtual PageAuditRequest? PageAuditRequest { get; set; }
        public virtual Status? Status { get; set; }
        public virtual ICollection<PageAuditItem> PageAuditItems { get; set; }  
    }
}
