// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using RCommon.Entities;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Domain.SEO.Lighthouse.Models
{
    public partial class PageAuditRequest : BusinessEntity<Guid>
    {
        public PageAuditRequest()
        {
            PageAudits = new HashSet<PageAudit>();
        }

        public PageAuditRequest(Guid id, Guid lighthouseProfileId, string pageUrl, DateTime createdDate, Guid statusId)
        {
            Id=id;
            LighthouseProfileId=lighthouseProfileId;
            PageUrl=pageUrl;
            CreatedDate=createdDate;
            StatusId=statusId;
        }

        public Guid LighthouseProfileId { get; set; }
        public string PageUrl { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid StatusId { get; set; }

        public virtual LighthouseProfile LighthouseProfile { get; set; }
        public virtual ICollection<PageAudit> PageAudits { get; set; }
    }
}
