// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using RCommon.Entities;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Domain.SEO.Lighthouse.Models
{
    public partial class Status : BusinessEntity<Guid>
    {
        public Status()
        {
            PageAuditItems = new HashSet<PageAuditItem>();
            PageAudits = new HashSet<PageAudit>();
        }

        public Status(Guid id, string statusName, Guid statusTypeId)
        {
            PageAuditItems = new HashSet<PageAuditItem>();
            PageAudits = new HashSet<PageAudit>();
            Id=id;
            StatusName=statusName;
            StatusTypeId=statusTypeId;
        }

        public string StatusName { get; set; }
        public Guid StatusTypeId { get; set; }

        public virtual StatusType StatusType { get; set; }
        public virtual ICollection<PageAuditItem> PageAuditItems { get; set; }
        public virtual ICollection<PageAudit> PageAudits { get; set; }
    }
}
