// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using RCommon.Entities;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Domain.SEO.Lighthouse.Models
{
    public partial class StatusType : BusinessEntity<Guid>
    {
        public StatusType()
        {
            Statuses = new HashSet<Status>();
        }

        public StatusType(Guid id, string statusTypeName)
        {
            Statuses = new HashSet<Status>();
            Id=id;
            StatusTypeName=statusTypeName;
        }

        public string StatusTypeName { get; set; }

        public virtual ICollection<Status> Statuses { get; set; }
    }
}
