// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using MotherStar.Platform.Domain.SEO.Lighthouse.Models;
using MotherStar.Platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MotherStar.Platform.Data.Configurations;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Data.Configurations
{
    public partial class PageAuditItemConfiguration : IEntityTypeConfiguration<PageAuditItem>
    {
        public void Configure(EntityTypeBuilder<PageAuditItem> entity)
        {
            BaseConfiguration.Configure(entity);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnType("text");

            entity.Property(e => e.Details)
                .IsRequired()
                .HasColumnType("text");

            entity.Property(e => e.ReferenceId)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.PageAudit)
                .WithMany(p => p.PageAuditItems)
                .HasForeignKey(d => d.PageAuditId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PageAuditItems_PageAudits");

            entity.HasOne(d => d.Status)
                .WithMany(p => p.PageAuditItems)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PageAuditItems_Statuses");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PageAuditItem> entity);
    }
}
