// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using MotherStar.Platform.Domain.SEO.Lighthouse.Models;
using MotherStar.Platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MotherStar.Platform.Data.Configurations;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Data.Configurations
{
    public partial class StatusTypeConfiguration : IEntityTypeConfiguration<StatusType>
    {
        public void Configure(EntityTypeBuilder<StatusType> entity)
        {
            BaseConfiguration.Configure(entity);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.StatusTypeName)
                .IsRequired()
                .HasMaxLength(100);

            OnConfigurePartial(entity);

            this.EnsureSeedData(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StatusType> entity);

        private void EnsureSeedData(EntityTypeBuilder<StatusType> entity)
        {
            entity.HasData(new StatusType(new Guid("31BFC614-8575-4CC1-89E5-0B2090D62358"), "Page Audit Requests"));
            entity.HasData(new StatusType(new Guid("C7C12605-F0C5-457F-9B76-3FB03D0527DF"), "Page Audits"));
            entity.HasData(new StatusType(new Guid("202B50FF-4E0B-4A4F-8542-6C7641114CB6"), "Page Audit Items"));
        }
    }
}
