// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using MotherStar.Platform.Domain.SEO.Lighthouse.Models;
using MotherStar.Platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MotherStar.Platform.Data.Configurations;
using System;
using System.Collections.Generic;

namespace MotherStar.Platform.Data.Configurations
{
    public partial class StatusConfiguration : IEntityTypeConfiguration<Status>
    {
        public void Configure(EntityTypeBuilder<Status> entity)
        {
            BaseConfiguration.Configure(entity);
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.StatusType)
                .WithMany(p => p.Statuses)
                .HasForeignKey(d => d.StatusTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Statuses_StatusTypes");

            OnConfigurePartial(entity);

            this.EnsureSeedData(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Status> entity);

        private void EnsureSeedData(EntityTypeBuilder<Status> entity)
        {
            entity.HasData(new Status(new Guid("C16CA33C-2949-4F88-82F2-36EB24BBF874"), "Started", new Guid("31BFC614-8575-4CC1-89E5-0B2090D62358")));
            entity.HasData(new Status(new Guid("C7625069-2055-4669-A0F2-5169B20EBC6E"), "Created", new Guid("31BFC614-8575-4CC1-89E5-0B2090D62358")));
            entity.HasData(new Status(new Guid("48A62047-2F22-453C-AB16-590DAFA383B1"), "Failed", new Guid("31BFC614-8575-4CC1-89E5-0B2090D62358")));
            entity.HasData(new Status(new Guid("CCCAE8E9-350C-43C5-BF0C-5D0D7FE1409C"), "Completed", new Guid("31BFC614-8575-4CC1-89E5-0B2090D62358")));
            entity.HasData(new Status(new Guid("67F8BDC0-04CA-448F-A5B1-46AEA7C569C3"), "Completed", new Guid("C7C12605-F0C5-457F-9B76-3FB03D0527DF")));
            entity.HasData(new Status(new Guid("C8CC655B-0DE4-484A-ABF2-4E8C659059F4"), "Completed", new Guid("202B50FF-4E0B-4A4F-8542-6C7641114CB6")));
        }
    }
}
